### ISSUE TITLE
https://go.uber.org/dig is not found

### ISSUE THREAD

**Issue by TakayukiCho** [uber-go/dig#183] opened 2018-03-06 07:31 UTC
![image](https://user-images.githubusercontent.com/8915906/37019502-d025545e-215b-11e8-9b07-090597d29754.png)

**Comment by breerly** [comment] 2018-03-06 07:44
Duplicate of https://github.com/uber/go.uber.org/issues/32

**Closed by breerly** 2018-03-06 07:44 UTC
